Задача 12. Экспериментальное исследование алгоритмов КС достижимости.
JetBrains-Research/formal-lang-course pull request #17
Opened 2021-11-10 13:09 UTC by gsvgit

2021-11-10 14:46 UTC, EgorOrachyov commented on tasks/task12.md
> +  - алгоритм выполнения регулярных запросов, реализованный с использованием pyCuBool (работа 5). Здесь только для RDF и регулярных запросов.
@gsvgit Если правильно понял, но цель - сравнение разных алгоритмов в их разных реализациях:
Хеллингс (ЦПУ), Матричный (ГПУ), Тензорный (ГПУ) - для cfpq 
Хеллингс (ЦПУ), Матричный (ГПУ), Тензорный (ГПУ), Тензорный-rpq (ГПУ) - для cfpq? 

Это извечная проблема позиционирования алгоритмов, т.е. я к тому, что как бы нам цель сформулировать так,
чтобы потом ребята внятные выводы написали.

2021-11-10 14:54 UTC, gsvgit commented on tasks/task12.md
> +  - алгоритм выполнения регулярных запросов, реализованный с использованием pyCuBool (работа 5). Здесь только для RDF и регулярных запросов.
@EgorOrachyov 
1. Забыл ЦПУ алгоритмы. Только что добавил.
2. Вообще, глобальные цели две. 1) Сравнить между собой различные алгоритмы для КС, реализованные с использованием одних и тех же библиотек (сравнить все ЦПУ между собой, сравнить все ГПУ между собой). 2) Оценить, на сколько хуже (или не хуже) использовать каждый из алгоритмов для КС для того, чтобы решать регулярные запросы. Чтобы ребята что-то поняли про то, что иногда специализированные алгоритмы всё же нужны (или не нужны).

2021-11-10 15:04 UTC, EgorOrachyov commented on tasks/task12.md
> +  - алгоритм выполнения регулярных запросов, реализованный с использованием pyCuBool (работа 5). Здесь только для RDF и регулярных запросов.
@gsvgit Вот да, тогда может в задачи это добавить:

Задача посвящена анализу производительности различных алгоритмов решения задачи достижимости с контекстно-свободными ограничениями: алгоритма Хеллингса, матричного алгоритма, тензорного алгоритма.
Цель: 
- Сравнение производительности реализаций различных алгоритмов для одной аппаратной платформы (CPU, GPU), для определения более производительного алгоритма в рамках одной платформы
- Сравнение производительности различных реализаций алгоритмов для разных платформ (CPU vs. GPU), для определения наиболее производительной реализации
- Сравнение производительности CFPQ алгоритмов со специализированными RPQ алгоритмами в задаче RPQ анализа, для определения необходимости существования решения для частных случаев

2021-11-10 15:48 UTC, gsvgit commented on tasks/task12.md
> +  - алгоритм выполнения регулярных запросов, реализованный с использованием pyCuBool (работа 5). Здесь только для RDF и регулярных запросов.
@EgorOrachyov Да, добавил. Спасибо!

2021-11-10 15:57 UTC, EgorOrachyov approved these changes

2021-11-11 10:56 UTC, vdshk requested changes
Думаю стоит поподробнее описать КАК должен ставиться эксперимент (что оценивается, с какой точностью, сколько замеров), чтобы не было проблем как в прошлый раз.

2021-11-11 10:56 UTC, vdshk commented on tasks/task12.md
> +  - Что и как замерялось
```suggestion
  - Что и как замерялось (количество экспериментов, точность замеров, единицы измерения)
```

2021-11-17 13:23 UTC, gsvgit commented
@vdshk @EgorOrachyov, А может просто https://pypi.org/project/pytest-benchmark/ жахнуть?

2021-11-17 13:57 UTC, vdshk commented
> @vdshk @EgorOrachyov, А может просто https://pypi.org/project/pytest-benchmark/ жахнуть?

В Юпитер тетрадках вряд ли получится запустить

2021-11-17 14:34 UTC, gsvgit commented
Да как так-то (

2021-11-18 09:02 UTC, gsvgit commented
"Помните, что время работы --- это случайная величина. Ваша задача оценить эту случайную величину на основе конечной выборки. А значит, пришло время использовать математическую статистику. Укажите в отчёте, какими именно инструментами математической статистики Вы пользовались."

2021-11-18 12:16 UTC, vdshk commented
> > @vdshk @EgorOrachyov, А может просто https://pypi.org/project/pytest-benchmark/ жахнуть?
> 
> В Юпитер тетрадках вряд ли получится запустить

Может запуститься с помощью [ipytest](https://github.com/chmp/ipytest)

2021-11-25 12:09 UTC, vdshk reviewed
небольшие замечания

2021-11-25 12:09 UTC, vdshk commented on tasks/task12.md
> +  - [ ] Выбрать графы bzip, gzip, ls, init, drivers, arch. Это графа, построенные по реальным программам и предназначенные для решения задач статического анализа.
```suggestion
  - [ ] Выбрать графы bzip, gzip, ls, init, drivers, arch. Это графы, построенные по реальным программам и предназначенные для решения задач статического анализа.
```

2021-11-25 12:09 UTC, vdshk commented on tasks/task12.md
> +  - [ ] Для статического анализа использовать единственны запрос. Обратите внимание, что он записан в максимально общем виде и непосредственно грамматика будет зависеть от алгоритма, который будет ис
```suggestion
  - [ ] Для статического анализа использовать единственный запрос. Обратите внимание, что он записан в максимально общем виде и непосредственно грамматика будет зависеть от алгоритма, который будет исследоваться.
```

2021-11-25 12:09 UTC, vdshk commented on tasks/task12.md
> +- [ ] Сделать notebook доступным по ссылке (не забыть проверить, что выданы пава на комментирование)
```suggestion
- [ ] Сделать notebook доступным по ссылке (обязательно выдать права на комментирование проверяющему)
```

2021-11-25 12:19 UTC, merged